name: Build GDrive CLI

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v2
      with:
        go-version: 1.12
      id: go

    - name: Check out repository
      uses: actions/checkout@v2

    - name: Get https://github.com/gdrive-org/gdrive code
      run: |
        export GOPATH=$HOME/go
        export GOBIN=$(go env GOPATH)/bin
        export PATH=$PATH:$GOPATH
        export PATH=$PATH:$GOBIN
        mkdir -p $GOPATH/pkg
        mkdir -p $GOBIN
        go get github.com/gdrive-org/gdrive

    - name: Add support for MIPS and MIPSLE
      run: |
        cd $HOME/go/src/github.com/prasmussen/gdrive/vendor/github.com/soniakeys/graph
        sed -i "s/+build 386 arm/+build 386 arm mips mipsle/g" bits32.go
        sed -i "s/+build \!386,\!arm/+build \!386,\!arm,\!mips,\!mipsle/g" bits64.go
    
    - name: Change CLIENT ID & SECRET
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      run: |
        cd $HOME/go/src/github.com/gdrive-org/gdrive/
        sed -i "s/367116221053-7n0vf5akeru7on6o2fjinrecpdoe99eg.apps.googleusercontent.com/$CLIENT_ID/g" handlers_drive.go
        sed -i "s/1qsNodXNaWq1mQuBjUjmvhoO/$CLIENT_SECRET/g" handlers_drive.go

    - name: Build
      run: |
        cp -r build/* $HOME/go/src/github.com/gdrive-org/gdrive/
        cd $HOME/go/src/github.com/gdrive-org/gdrive/
        chmod +x build-selected.sh
        chmod +x build.sh
        ./build-selected.sh
        ls -al _release/bin

    - name: Copy release file
      run: |
        mkdir release
        cp -r $HOME/go/src/github.com/gdrive-org/gdrive/_release/bin/* release

    - name: Save build file to artifact
      uses: actions/upload-artifact@v1
      with:
        name: release
        path: release
